const endingsPatterns = [
  {key: 0, gender: 0, rule: 'phone', exceptions: []},
  {key: 1, gender: 1, rule: 'ence', exceptions: ['silence']},
  {key: 2, gender: 1, rule: 'euse', exceptions: []},
  {key: 3, gender: 1, rule: 'ance', exceptions: []},
  {key: 4, gender: 1, rule: 'esse', exceptions: []},
  {key: 5, gender: 1, rule: 'ique', exceptions: ['graphique', 'périphérique', 'plastique', 'moustique']},
  {key: 6, gender: 1, rule: 'ière', exceptions: ['arrière', 'cimetière', 'derrière']},
  {key: 7, gender: 1, rule: 'erie', exceptions: []},
  {key: 8, gender: 0, rule: 'ueil', exceptions: []},
  {key: 9, gender: 0, rule: 'isme', exceptions: []},
  {key: 10, gender: 0, rule: 'ment', exceptions: ['jument']},
  {key: 11, gender: 1, rule: 'rice', exceptions: ['dentifrice']},
  {key: 12, gender: 0, rule: 'cide', exceptions: []},
  {key: 13, gender: 0, rule: 'tre', exceptions: ['fenêtre', 'huître', 'lettre', 'montre', 'rencontre', 'vitre']},
  {key: 14, gender: 0, rule: 'ège', exceptions: []},
  {key: 15, gender: 0, rule: 'ard', exceptions: []},
  {key: 16, gender: 0, rule: 'age', exceptions: ['cage', 'image', 'nage', 'page', 'plage', 'rage']},
  {key: 17, gender: 0, rule: 'ble', exceptions: ['cible', 'étable', 'fable', 'table']},
  {key: 18, gender: 0, rule: 'cle', exceptions: ['boucle']},
  {key: 19, gender: 0, rule: 'ing', exceptions: []},
  {key: 20, gender: 0, rule: 'ste', exceptions: ['liste', 'modiste', 'piste']},
  {key: 21, gender: 0, rule: 'one', exceptions: []},
  {key: 22, gender: 0, rule: 'ope', exceptions: []},
  {key: 23, gender: 0, rule: 'oir', exceptions: []},
  {key: 24, gender: 0, rule: 'ail', exceptions: []},
  {key: 25, gender: 0, rule: 'eil', exceptions: []},
  {key: 26, gender: 0, rule: 'eau', exceptions: ['eau', 'peau']},
  {key: 27, gender: 0, rule: 'ème', exceptions: []},
  {key: 28, gender: 1, rule: 'ère', exceptions: ['père', 'frère']},
  {key: 29, gender: 1, rule: 'son', exceptions: ['blouson']},
  {key: 30, gender: 1, rule: 'tié', exceptions: []},
  {key: 31, gender: 1, rule: 'ude', exceptions: ['coude', 'interlude', 'prélude']},
  {key: 32, gender: 1, rule: 'ule', exceptions: ['préambule', 'scrupule', 'tentacule', 'testicule', 'véhicule', 'ventricule', 'vestibule']},
  {key: 33, gender: 1, rule: 'ure', exceptions: ['centaure', 'cyanure', 'dinosaure', 'murmure']},
  {key: 34, gender: 1, rule: 'ace', exceptions: ['ace', 'palace']},
  {key: 35, gender: 1, rule: 'ade', exceptions: ['grade', 'jade', 'stade']},
  {key: 36, gender: 1, rule: 'ale', exceptions: ['châle', 'pétale', 'scandale']},
  {key: 37, gender: 1, rule: 'ine', exceptions: ['capitaine', 'domaine', 'moine', 'magazine', 'patrimoine']},
  {key: 38, gender: 1, rule: 'ion', exceptions: ['avion', 'bastion', 'billion', 'camion', 'cation', 'dominion', 'espion', 'ion', 'lampion', 'lion', 'million', 'morpion', 'pion', 'scion', 'scorpion', 'trillion']},
  {key: 39, gender: 1, rule: 'ire', exceptions: ['auditoire', 'commentaire', 'dictionnaire', 'directoire', 'horaire', 'itinéraire', 'ivoire', 'laboratoire', 'navire', 'pourboire', 'purgatoire', 'répertoire', 'salaire', 'sommaire', 'sourire', 'territoire', 'vocabulaire']},
  {key: 40, gender: 1, rule: 'ise', exceptions: []},
  {key: 41, gender: 1, rule: 'ite', exceptions: ['anthracite', 'ermite', 'granite', 'graphite', 'mérite', 'opposite', 'plébiscite', 'rite', 'satellite', 'site', 'termite']},
  {key: 42, gender: 1, rule: 'lle', exceptions: ['braille', 'gorille', 'intervalle', 'mille', 'portefeuille', 'vaudeville', 'vermicelle', 'violoncelle']},
  {key: 43, gender: 1, rule: 'mme', exceptions: ['dilemme', 'gramme', 'programme']},
  {key: 44, gender: 1, rule: 'nde', exceptions: ['monde']},
  {key: 45, gender: 1, rule: 'nne', exceptions: []},
  {key: 46, gender: 1, rule: 'ole', exceptions: ['contrôle', 'monopole', 'rôle', 'symbole']},
  {key: 47, gender: 1, rule: 'rre', exceptions: ['beurre', 'parterre', 'tonnerre', 'verre']},
  {key: 48, gender: 0, rule: 'de', exceptions: ['bride', 'merde', 'méthode', 'pinède', 'ade, -nde, -ude endings']},
  {key: 49, gender: 1, rule: 'ée', exceptions: ['lycée', 'musée']},
  {key: 50, gender: 0, rule: 'et ', exceptions: []},
  {key: 51, gender: 0, rule: 'ot', exceptions: []},
  {key: 52, gender: 0, rule: 'at', exceptions: []},
  {key: 53, gender: 0, rule: 'il', exceptions: []},
  {key: 54, gender: 0, rule: 'me', exceptions: ['alarme', 'âme', 'arme', 'cime', 'coutume', 'crème', 'écume', 'énigme', 'estime', 'ferme', 'firme', 'forme', 'larme', 'plume', 'rame', 'rime']},
  {key: 55, gender: 0, rule: 'ou', exceptions: []},
  {key: 56, gender: 1, rule: 'be', exceptions: ['cube', 'globe', 'microbe', 'tube', 'verbe']},
  {key: 57, gender: 1, rule: 'ce', exceptions: ['artifice', 'armistice', 'appendice', 'bénéfice', 'caprice', 'commerce', 'dentifrice', 'divorce', 'exercice', 'office', 'orifice', 'précipice', 'prince', 'sacrifice', 'service', 'silence', 'solstice', 'supplice', 'vice']},
  {key: 58, gender: 1, rule: 'cé', exceptions: ['crustacé']},
  {key: 59, gender: 1, rule: 'ee', exceptions: ['pedigree']},
  {key: 60, gender: 1, rule: 'ée', exceptions: ['apogée', 'lycée', 'musée', 'périgée', 'trophée']},
  {key: 61, gender: 1, rule: 'fe', exceptions: ['golfe']},
  {key: 62, gender: 1, rule: 'ie', exceptions: ['incendie', 'foie', 'génie', 'parapluie', 'sosie']},
  {key: 63, gender: 1, rule: 'se', exceptions: ['carosse', 'colosse', 'gypse', 'inverse', 'malaise', 'pamplemousse', 'parebrise', 'suspense']},
  {key: 64, gender: 1, rule: 'sé', exceptions: ['exposé', 'opposé']},
  {key: 65, gender: 1, rule: 'té', exceptions: ['arrêté', 'comité', 'comté', 'côté', 'député', 'été', 'pâté', 'traité']},
  {key: 66, gender: 1, rule: 'ue', exceptions: ['abaque']},
  {key: 67, gender: 1, rule: 'e', exceptions: ['peuple']},
  {key: 68, gender: 0, rule: 'o', exceptions: ['dactylo', 'dynamo', 'libido', 'radio']}, //most of these are apocopes of longer feminine words
  {key: 69, gender: 0, rule: 'i', exceptions: ['foi', 'fourmi', 'loi', 'paroi', 'merci']},
  {key: 70, gender: 0, rule: 'é', exceptions: ['clé', 'psyché', 'sé, té, and tié endings']},
  {key: 71, gender: 0, rule: 'u', exceptions: ['tribu', 'vertu']},
  {key: 72, gender: 0, rule: 'a', exceptions: ['cafétéria', 'pizza' ]},
];

const consonantPattern = [
  {key: 73, gender: 0, rule: 'Words ending in consonants (in the spelling) are usually masculine.', exceptions: ['mob', 'pub', 'alloc', 'collec', 'doc', 'embroc', 'fac', 'réduc', 'soif', 'clef', 'nef', 'façon', 'fin', 'leçon', 'main', 'maman', 'rançon', 'chair', 'cour', 'cuiller', 'mer', 'tour', 'brebis', 'fois', 'oasis', 'souris', 'vis', 'burlat', 'dent', 'dot', 'forêt', 'mort', 'nuit', 'part', 'plupart', 'ziggourat', 'roseval', 'faim', 'croix', 'noix', 'paix', 'toux', 'voix']},
]

const conceptualPatterns = [
  {key: 74, gender: 0, rule: 'Words ending in other consonants (in the spelling).', matches: []},
  {key: 75, gender: 0, rule: 'Certain nouns referring to animals that can refer to only the male of the species. For example: étalon (stallion), cerf (stag), matou (tomcat).', matches: ['étalon', 'stag', 'matou']},
  {key: 76, gender: 0, rule: 'Masculine nouns that are \'generic\' terms and can refer to either a male or female of the species. For example, le cheval can refer to either a male or female horse.', matches: ['cheval']},
  {key: 77, gender: 0, rule: 'Names of towns. Other place names (departments, rivers, countries) not ending in -e. Sometimes town names, especially if they look or sound feminine (e.g. Marseilles ending in -es), can be treated as feminine. This is quite rare, though.', matches: ['Mexique', 'Combodge', 'Rhône', 'Finistère', 'Zimbabwe', 'Norvège']},
  {key: 78, gender: 0, rule: 'Nouns ending in eur, generally derived from a verb, denoting people, professions, machines carrying out an activity or scientific things: aspirateur, facteur, ordinateur', matches: ['aspirateur', 'facteur', 'ordinateur']},
  {key: 79, gender: 0, rule: 'Compound nouns of the form verb-noun: porte-monnaie, pare-brise, tire-bouchon.', matches: ['porte-monnaie', 'pare-brise', 'tire-bouchon']},
  {key: 80, gender: 0, rule: 'Nouns referring to male people.', matches: ['adulte', 'homme', 'père', 'frère', 'oncle', 'cousin', 'garçon']},
  {key: 81, gender: 0, rule: 'A handful of nouns are masculine, whatever the gender of the person they refer to, e.g.: amateur, artiste, auteur, nudiste, témoin, vainqueur, voyou plus certain job titles.', matches: ['amateur', 'artiste', 'auteur', 'adolescent', 'nudiste', 'témoin', 'vainqueur', 'voyou']},
  {key: 82, gender: 1, rule: 'Place names ending in -e.', matches: ['Franche-Comté', 'Belize', 'Cambodge', 'Mexique', 'Mozambique', 'Zaïre', 'Zimbabwe']},
  {key: 83, gender: 1, rule: 'Nouns referring to female people.', matches: ['femme', 'fille', 'tante', 'mère', 'sœur', 'fille']},
  {key: 84, gender: 1, rule: 'These are feminine, whatever the gender of the person: personne, victime, recrue (recruit), connaissance (acquaintance).', matches: ['personne', 'victime', 'recrue', 'connaissance']},
  {key: 85, gender: 1, rule: 'Certain nouns referring to animals that can refer to only the female of the species. For example: chatte (female cat), chienne (bitch), louve (she-wolf).', matches: ['chatte', 'chienne', 'louve']},
  {key: 86, gender: 1, rule: 'Feminine nouns that are \'generic\' terms and can refer to either male or female of the species. For example, la souris can refer to either a male or female mouse.', matches: []},
  {key: 87, gender: 1, rule: 'Most other endings consisting of Vowel + Consonant + e: -ine, -ise, -alle, -elle, -esse, -ette etc', matches: ['episode', 'espace', 'intervalle', 'mille', 'magazine', 'réverbère', 'squelette']},
  {key: 88, gender: 1, rule: 'Figurative nouns ending in -eur, usually derived from an adjective: rougeur, largeur, pâleur, couleur, horreur, rumeur', matches: []},
  {key: 89, gender: 1, rule: 'Words for durations of time are feminine', matches: ['journée', 'année', 'soirée', 'matinée', 'nuitée']},
  {key: 90, gender: 1, rule: 'Words for points in time are masculine', matches: ['jour', 'an', 'soir', 'matin']},
  {key: 91, gender: 1, rule: 'Apocopes are words which drop part of the end. Think of \'cred\' for credit or \'mag\' for magazine in English. Apocopes in French usually take the gender of their source words.', matches: ['santiag', 'métro', 'vélo', 'auto', 'accu', 'actu', 'ado', 'appart', 'ciné', 'fac', 'manif', 'météo', 'moto']},
  {key: 92, gender: 0, rule: 'Most untraslated foreign words are masculine', matches: []},

];

module.exports = {
  conceptualPatterns: conceptualPatterns,
  endingsPatterns: endingsPatterns,
}
